import React, { useEffect, useState } from "react";
import {
  Accordion, FormControlLabel, Checkbox,
  AccordionDetails,
  AccordionSummary,
  Box, NumberInput,
  Button,
  Modal, FormControl, Select, MenuItem, InputLabel,
  TextField,
  Typography,
  Popover,
  Autocomplete,
} from "@mui/material";
import { DateTimePicker } from '@mui/x-date-pickers';
import { LocalizationProvider } from '@mui/x-date-pickers-pro';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import Draggable, { DraggableCore } from "react-draggable";
import mapimg from "../../../Assets/mapgroup.png";
import { useNavigate, useLocation } from "react-router-dom";
import AuditorHeader from "../AuditorHeader/AuditorHeader";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import AxiosApp from "../../../common/AxiosApp";
import CustomAlerts from "../../../common/CustomAlerts";
import CustomLoader from "../../../common/customLoader";
import L, { icon } from "leaflet";
import { url1 } from "../../../App";
import JSZip from 'jszip';
import InfoOutlineIcon from '@mui/icons-material/InfoOutlined';

var map = ""

var comboList = {};
var comboIDList = {};
var comboIRC = {};
var imageList = {};
var gpsLive = ['', '']
navigator.geolocation.getCurrentPosition((position) => {
  gpsLive[0] = position.coords.latitude.toFixed(5);
  gpsLive[1] = position.coords.longitude.toFixed(5);
});
const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: "90%",
  height: "60vh",
  bgcolor: "background.paper",
  borderRadius: "10px",
  // border: "2px solid #000",
  // boxShadow: 24,
  overflowY: "auto",
  scrollBehavior: "smooth",
  p: 4,
};
var gpsLive = ['', '']
navigator.geolocation.getCurrentPosition((position) => {
  gpsLive[0] = position.coords.latitude.toFixed(5);
  gpsLive[1] = position.coords.longitude.toFixed(5);
});
function SurveyformTwo() {
  const [popcontent, setPopContent] = React.useState('')
  const [anchorEl, setAnchorEl] = React.useState(null);

  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose1 = () => {
    setAnchorEl(null);
  };

  const open1 = Boolean(anchorEl);
  const id = open1 ? 'simple-popover' : undefined;

  const navigate = useNavigate();
  const { state } = useLocation()

  console.log("imagelist", imageList);
  //common
  const [isload, setIsload] = useState("");
  const [alert, setAlert] = useState("");
  const [alertMsg, setAlertMsg] = useState("");
  const [dummy, setDummy] = useState(0)
  const [gpsAutoValue, setgpsAutoValue] = useState([])
  //float map
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  const [auditorGeo, setAuditorGeo] = React.useState("")
  const [stretchGeo, setStretchGeo] = React.useState("")

  const [comboMap, setcomboMap] = React.useState(new Map())
  const [checkMap, setcheckMap] = React.useState(new Map())

  const findDatatype = (x) => {
    //if custom, its textbox
    //if mastertable, its combobox
    //if dependency is there, make sure to call another api to address dependency 
    let k1 = Object.keys(x)
    let v1 = Object.values(x)
    /**
     * C.E.B.2: "Chainage (km)"
        conditions: "NA"
        data_type: "Numerical (Special Character)"
        field_type: "Optional"
        functionality: "Numerical Box"
        irc_help_tool: "Enter the Chainage Value in this Format (170+000)"
        master_table: "Custom"
     */
    console.log(v1, 'v1')
    let v2 = v1[4]
    if (v1[7] == "DD/MM/YY,hh:mm") {
      return datefield1(x)
    } else if (v2 == "Dropdown/ Radio Button") {
      return combo(x)
    } else if (v2 == "Numerical Box") {
      return decimal(x)
    } else if (v2 == "Autogenerated") {
      return gpsAuto(x)
    } else if (v2 == "Text Area") {
      return multiline(x)
    } else if (v2 == "Checkbox" || v2 == "Check Box") {
      return checkbox(x)
    } else if (v2 == "Camera/ Upload") {
      return upload(x)
    } else {
      return (<></>)
    }
    //for latlong, use upload button
  }
  // const handleSaveSection = () => {
  //   //form the data to post
  //   let local = state.details
  //   let payload1 = {}
  //   let temp = "";
  //   let rt = [];
  //   let imageFilenames = [];
  //   let forObs = [];
  //   let formData = new FormData();
  //   for (let index = 0; index < local.length; index++) {
  //     const element = local[index];
  //     let id = Object.keys(element)[0]
  //     let value = element.functionality;
  //     console.log(value,"valuevalue")
  //     switch (value) {
  //       case "Dropdown/ Radio Button": {
  //         temp = document.getElementById(id).innerText
  //         payload1[id] = temp;
  //         break;
  //       }
  //       case "Text Area":
  //       case "Numerical Box":
  //       case "Autogenerated": { //gps
  //         temp = document.getElementById(id).value
  //         payload1[id] = temp;
  //         break;
  //       }
  //       case "Checkbox": {
  //         temp = document.getElementById(id).checked
  //         payload1[id] = temp;
  //         if (temp) {
  //           forObs.push(element[id])
  //         }
  //         break;
  //       }
  //       case "Camera/ Upload": {
  //         console.log(imageList[id])
  //         imageFilenames.push(imageList[id]["fname1"])
  //         formData.append([imageList[id]["fname1"]], imageList[id]["image1"])
  //         temp = "image";
  //         payload1[id] = "Image";
  //         break;
  //       }
  //     }
  //     if (element.field_type == "Mandatory" && value != "Checkbox") {
  //       if (temp == "") {
  //         setAlert("error")
  //         setAlertMsg("Mandatory fields are not entered")
  //         return;
  //       }
  //     }

  //     //Issues/Landuse Category/ Roadside Hazard Category/ User Behaviour Category
  //     let cd1 = element.conditions;
  //     if (cd1 == "NA" &&
  //       (element[id] == "Issues" || element[id] == "Roadside Hazard Category" ||
  //         element[id] == "Landuse Category" || element[id] == "User Behaviour Category"
  //       )) { //non dependency dropdown Issues
  //       let str1 = "";
  //       try {
  //         let s1 = document.getElementById(id).innerText
  //         //search s1 in comboIDList
  //         let index1 = comboList[id].indexOf(s1)
  //         if (index1 != -1) {
  //           str1 = id + "." + (index1 + 1)
  //         }
  //       } catch (error) {
  //       }
  //       rt.push(str1)
  //     }

  //     //2 level works fine.
  //     //3 level works only for road marking 
  //     //3 level not works for road sign---handled the hack in below
  //     //remove the hack once Road Sign => Issues => conditions => becomes != NA

  //     if ((cd1 != "NA" && cd1 != "No") //dependency dropdown condition
  //     ) {
  //       cd1 = cd1.split(" ")[1]
  //       let s1 = document.getElementById(cd1).innerText
  //       let str1 = "";
  //       let str2 = "";
  //       //search s1 in comboIDList
  //       let index1 = comboList[cd1].indexOf(s1)
  //       if (index1 != -1) {
  //         str1 = comboIDList[cd1][index1]
  //       }

  //       let s2 = document.getElementById(id).innerText
  //       //search s2 in comboIDList
  //       index1 = comboList[id].indexOf(s2)
  //       if (index1 != -1) {
  //         str2 = comboIDList[id][index1]
  //       }
  //       let str3 = ""
  //       if (str1 == "" && str2 != "") {
  //         str3 = str2;
  //       }
  //       else if (str1 != "" && str2 == "") {
  //         str3 = str1;
  //       }
  //       else {
  //         str3 = str1.concat(".").concat(str2)
  //         //rt.push(str1);rt.push(str2)
  //       }
  //       rt.push(str3)
  //     }
  //   }
  //   if (imageFilenames.length == 1) {
  //     payload1["file_name"] = imageFilenames;
  //   }

  //   //axios post
  //   let section = (Object.keys(state.details[0])[0]).split(".")[2]

  //   if (rt.length == 2) {
  //     if (state.sectionName != "Road Sign") { //hack here for road sign
  //       let a1 = rt[0];
  //       let a2 = rt[1];
  //       let a11 = a1.split(".").splice(5)
  //       let a21 = a2.split(".").splice(5)
  //       rt = [a11.concat(a21).join(".")]
  //     }
  //     else { //works for road markings
  //       let a1 = rt[0];
  //       let a2 = rt[1];
  //       let a11 = a1.split(".").splice(5)
  //       let a21 = a2.split(".")
  //       rt = [a11.concat(a21).join(".")]
  //     }
  //   }

  //   console.log(rt)
  //   formData.append("audit_id", state.auditObj.audit_id)
  //   formData.append("auditor_id", state.auditObj.auditor)
  //   formData.append("section_id", section)
  //   formData.append("answers", JSON.stringify(payload1))
  //   formData.append("retrieval_ids", JSON.stringify(rt))
  //   formData.append("submitted_on", new Date().toISOString().slice(0, 10).split('-').reverse().join('-'))

  //   //share gps
  //   let check1 = "";
  //   let check2 = ""
  //   try {
  //     check1 = Object.keys(local[0])[0]
  //     //if(check1.split(".")[3] == '1' && local[0][check1].search("GPS")> -1){
  //     if (local[0][check1].search("GPS") > -1) {
  //       check2 = document.getElementById(check1).value;
  //       // let regex = /^\d+\.\d+$/;
  //       // if(!(regex.test(check2))) {
  //       //   setAlert("error");
  //       //   setAlertMsg("Please enter correct format for GPS, eg:0.200");
  //       //   return;
  //       // }
  //     }
  //   } catch (error) {
  //   }
  //   //do string search and find the answer
  //   formData.append('gps_location', check2)

  //   //share chainage
  //   let v1 = ""
  //   try {
  //     if (document.querySelectorAll("[title*='Chainage']") &&
  //       document.querySelectorAll("[title*='Chainage']")[0] &&
  //       document.querySelectorAll("[title*='Chainage']")[0].getElementsByTagName("input") &&
  //       document.querySelectorAll("[title*='Chainage']")[0].getElementsByTagName("input")[0].value) {
  //       v1 = document.querySelectorAll("[title*='Chainage']")[0]
  //         .getElementsByTagName("input")[0].value;
  //       let regex = /^\d+\+\d+$/;
  //       if (!(regex.test(v1))) {
  //         setAlert("error");
  //         setAlertMsg("Please enter correct format for chainage, eg:0+200");
  //         return;
  //       } else {
  //         v1 = v1.replace("+", ".")
  //       }
  //     }
  //   } catch (error) {
  //   }
  //   //do string search and find the answer
  //   formData.append('chainage', v1)

  //   //share the category name
  //   v1 = {}
  //   v1[state.sectionName] = ""
  //   if (state.catNames[state.sectionName]) {
  //     v1[state.sectionName] = state.catNames[state.sectionName]
  //   }
  //   formData.append("sub_section", JSON.stringify(v1))

  //   //share general and critical observation
  //   if (forObs.length == 2) {
  //     forObs = "Both";
  //   }
  //   formData.append("obs_category", forObs)

  //   //share question '4' ends, road side
  //   check1 = "";
  //   check2 = "";
  //   try {
  //     check1 = Object.keys(local[3])[0]
  //     if (check1.split(".")[3] == '4' && local[3][check1] == "Road Side") {
  //       check2 = document.getElementById(check1).innerText;
  //     }
  //   } catch (error) {

  //   }
  //   formData.append("roadside", check2);
  //   const config = {
  //     headers: { 'content-type': 'multipart/form-data' }
  //   }

  //   formData.append("live_gps", gpsLive)
  //   console.log(formData)
  //   imageList = {};
  //   setIsload(true)
  //   window.setTimeout(function () {
  //     AxiosApp.post(url1 + "answer", formData, config)
  //       .then((response) => {
  //         setIsload(true)
  //         if (response.data.statusCode == "200") {
  //           setIsload(false);
  //           setAlert("success");
  //           setAlertMsg(response.data.status);
  //           navigate(-1, { state: { showObj: state.auditObj } })
  //         } else {
  //           setAlert("error");
  //           setAlertMsg(response.data.status);
  //           navigate(-1, { state: { showObj: state.auditObj } })
  //         }
  //       })
  //       .catch((error) => {
  //         setIsload(false);
  //         setAlert("error");
  //         setAlertMsg(error);
  //         navigate(-1, { state: { showObj: state.auditObj } })
  //       });
  //   }, 0)
  // }
  const handleSaveSection = () => {
    //form the data to post
    let local = state.details
    let payload1 = {}
    let temp = "";
    let rt = [];
    let imageFilenames = [];
    let forObs = [];
    let formData = new FormData();
  
    for (let index = 0; index < local.length; index++) {
      const element = local[index];
      let id = Object.keys(element)[0]
      let value = element.functionality;
      console.log(value,"valuevalue")
  
      switch (value) {
        case "Dropdown/ Radio Button": {
          let el = document.getElementById(id);
          temp = el ? (el.innerText || el.value || "").trim() : "";
  
          // Fallback to comboMap if DOM read fails (happens with Autocomplete)
          if (!temp && comboMap.has(id)) {
            temp = comboMap.get(id) || "";
          }
  
          payload1[id] = temp;
          break;
        }
  
        case "Text Area":
        case "Numerical Box":
        case "Autogenerated": { //gps
          let el = document.getElementById(id);
          temp = el ? el.value.trim() : "";
          payload1[id] = temp;
          break;
        }
  
        case "Checkbox": {
          let el = document.getElementById(id);
          temp = el ? el.checked : false;
          payload1[id] = temp;
          if (temp) {
            forObs.push(element[id])
          }
          break;
        }
  
        case "Camera/ Upload": {
          console.log(imageList[id])
          if (imageList[id] && imageList[id]["fname1"]) {
            imageFilenames.push(imageList[id]["fname1"])
            formData.append(imageList[id]["fname1"], imageList[id]["image1"])
            temp = "image";
            payload1[id] = "Image";
          }
          break;
        }
      }
  
      if (element.field_type == "Mandatory" && value != "Checkbox") {
        if (temp == "") {
          setAlert("error")
          setAlertMsg("Mandatory fields are not entered")
          return;
        }
      }
  
      // ────────────────────────────────────────────────
      // Issues / Landuse Category / Roadside Hazard Category / User Behaviour Category
      // ────────────────────────────────────────────────
      let cd1 = element.conditions;
      if (cd1 == "NA" &&
        (element[id] == "Issues" || element[id] == "Roadside Hazard Category" ||
          element[id] == "Landuse Category" || element[id] == "User Behaviour Category"
        )) {
        let str1 = "";
        try {
          let s1 = "";
          let el = document.getElementById(id);
          if (el) {
            s1 = el.innerText.trim();
          }
          // Fallback for Autocomplete
          if (!s1 && comboMap.has(id)) {
            s1 = comboMap.get(id) || "";
          }
  
          let index1 = comboList[id]?.indexOf(s1) ?? -1;
          if (index1 !== -1) {
            str1 = id + "." + (index1 + 1)
          }
        } catch (error) {
          console.warn("Error reading independent dropdown:", error);
        }
        if (str1) rt.push(str1);
      }
  
      // ────────────────────────────────────────────────
      // Dependency dropdown logic
      // ────────────────────────────────────────────────
      if ((cd1 != "NA" && cd1 != "No")) {
        cd1 = cd1.split(" ")[1]
        let s1 = "";
        let parentEl = document.getElementById(cd1);
        if (parentEl) {
          s1 = parentEl.innerText.trim();
        }
        // Fallback
        if (!s1 && comboMap.has(cd1)) {
          s1 = comboMap.get(cd1) || "";
        }
  
        let str1 = "";
        let index1 = comboList[cd1]?.indexOf(s1) ?? -1;
        if (index1 !== -1) {
          str1 = comboIDList[cd1][index1]
        }
  
        let s2 = "";
        let childEl = document.getElementById(id);
        if (childEl) {
          s2 = childEl.innerText.trim();
        }
        // Fallback for Autocomplete
        if (!s2 && comboMap.has(id)) {
          s2 = comboMap.get(id) || "";
        }
  
        let str2 = "";
        index1 = comboList[id]?.indexOf(s2) ?? -1;
        if (index1 !== -1) {
          str2 = comboIDList[id][index1]
        }
  
        let str3 = ""
        if (str1 == "" && str2 != "") {
          str3 = str2;
        }
        else if (str1 != "" && str2 == "") {
          str3 = str1;
        }
        else if (str1 && str2) {
          str3 = str1.concat(".").concat(str2)
        }
  
        if (str3) rt.push(str3);
      }
    }
  
    // ... rest of your code remains completely unchanged ...
  
    if (imageFilenames.length == 1) {
      payload1["file_name"] = imageFilenames;
    }
  
    //axios post
    let section = (Object.keys(state.details[0])[0]).split(".")[2]
  
    if (rt.length == 2) {
      if (state.sectionName != "Road Sign") {
        let a1 = rt[0];
        let a2 = rt[1];
        let a11 = a1.split(".").splice(5)
        let a21 = a2.split(".").splice(5)
        rt = [a11.concat(a21).join(".")]
      }
      else {
        let a1 = rt[0];
        let a2 = rt[1];
        let a11 = a1.split(".").splice(5)
        let a21 = a2.split(".")
        rt = [a11.concat(a21).join(".")]
      }
    }
  
    console.log(rt)
    formData.append("audit_id", state.auditObj.audit_id)
    formData.append("auditor_id", state.auditObj.auditor)
    formData.append("section_id", section)
    formData.append("answers", JSON.stringify(payload1))
    formData.append("retrieval_ids", JSON.stringify(rt))
    formData.append("submitted_on", new Date().toISOString().slice(0, 10).split('-').reverse().join('-'))
  
    //share gps
    let check1 = "";
    let check2 = ""
    try {
      check1 = Object.keys(local[0])[0]
      if (local[0][check1].search("GPS") > -1) {
        check2 = document.getElementById(check1)?.value || "";
      }
    } catch (error) {
    }
    formData.append('gps_location', check2)
  
    //share chainage
    let v1 = ""
    try {
      let chainageEls = document.querySelectorAll("[title*='Chainage'] input");
      if (chainageEls.length > 0) {
        v1 = chainageEls[0].value.trim();
        let regex = /^\d+\+\d+$/;
        if (v1 && !regex.test(v1)) {
          setAlert("error");
          setAlertMsg("Please enter correct format for chainage, eg:0+200");
          return;
        } else if (v1) {
          v1 = v1.replace("+", ".")
        }
      }
    } catch (error) {
    }
    formData.append('chainage', v1)
  
    //share the category name
    v1 = {}
    v1[state.sectionName] = ""
    if (state.catNames[state.sectionName]) {
      v1[state.sectionName] = state.catNames[state.sectionName]
    }
    formData.append("sub_section", JSON.stringify(v1))
  
    //share general and critical observation
    if (forObs.length == 2) {
      forObs = "Both";
    }
    formData.append("obs_category", forObs)
  
    //share question '4' ends, road side
    check1 = "";
    check2 = "";
    try {
      check1 = Object.keys(local[3])[0]
      if (check1.split(".")[3] == '4' && local[3][check1] == "Road Side") {
        let el = document.getElementById(check1);
        check2 = el ? (el.innerText || el.value || "") : "";
      }
    } catch (error) {
    }
    formData.append("roadside", check2);
  
    const config = {
      headers: { 'content-type': 'multipart/form-data' }
    }
  
    formData.append("live_gps", gpsLive)
    console.log(formData)
    imageList = {};
    setIsload(true)
  
    window.setTimeout(function () {
      AxiosApp.post(url1 + "answer", formData, config)
        .then((response) => {
          setIsload(false);  // fixed: was setIsload(true) before
          if (response.data.statusCode == "200") {
            setAlert("success");
            setAlertMsg(response.data.status);
            window.alert("Data saved successfully")
            navigate(-1, { state: { showObj: state.auditObj } })

          } else {
            setAlert("error");
            setAlertMsg(response.data.status);
            navigate(-1, { state: { showObj: state.auditObj } })
          }
        })
        .catch((error) => {
          setIsload(false);
          setAlert("error");
          setAlertMsg(error.message || "Save failed");
          navigate(-1, { state: { showObj: state.auditObj } })
        });
    }, 0)
  }
  
  const datefield1 = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (
      <FormControl fullWidth title={data.irc_help_tool}>
        <LocalizationProvider dateAdapter={AdapterDayjs}>

          <DateTimePicker required disableFuture label={l2[0]}
            //onChange={} 
            closeOnSelect={true}
            format="DD-MM-YYYY HH:mm"
            ampm={false}
            slotProps={{
              textField: {
                required: true,
                id: l1[0]
              },
            }} />
        </LocalizationProvider>
      </FormControl>
    )
  }
  const text = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (
      <TextField
        fullWidth id={l1[0]}
        label={l2[0]}
        required={data.field_type == "Mandatory"}
        variant="outlined" title={data.irc_help_tool}
      />
    )
  }
  const gpsAuto = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (<div style={{
      display: "flex"
    }}>
      <TextField id={l1[0]} label={l2[0]}
        title={data.irc_help_tool}
        required={data.field_type == "Mandatory"}
        value={gpsAutoValue}
        onChange={(e) => setgpsAutoValue(e.target.value)}
      />
      <Button onClick={(e) => setgpsAutoValue(gpsLive)}>Click to Fetch GPS Coordinates</Button></div>
    )
  }
  const decimal = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (
      <TextField id={l1[0]} label={l2[0]}
        title={data.irc_help_tool}
        required={data.field_type == "Mandatory"}
      />
    )
  }
  const multiline = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (
      <TextField
        fullWidth multiline
        label={l2[0]} id={l1[0]}
        required={data.field_type == "Mandatory"}
        variant="outlined" title={data.irc_help_tool}
      />
    )
  }
  const upload = (data) => {

    console.log("imageList", imageList);
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (
      <div style={{
        display: "flex"
      }}>
        <img
          style={{
            width: "200px",
            height: "200px",
            backgroundColor: "white",
            //backgroundImage: imageList && imageList[l1[0]] && imageList[l1[0]].url1,
          }}
          src={imageList && imageList[l1[0]] && imageList[l1[0]].url1}
          alt={""}
        />
        <Button
          onClick={(e) => {
            document.getElementById(l1[0]).click();
          }}
          title="Upload the file"
        >
          {"Upload"}
          {/* Upload {l2[0]} */}
        </Button>
        <input title={data.irc_help_tool}
          type="file"
          //accept="image/*"
          id={l1[0]}
          style={{ display: "none" }}
          onChange={(e) => {
            let image1 = e.target.files[0]
            let url1 = URL.createObjectURL(e.target.files[0]);
            //need to save as this 
            let fname1 = l1[0] + ".jpg"; //e.target.files[0].name;

            imageList[l1[0]] = { image1, url1, fname1 }

            const canvas = document.createElement('canvas');
            canvas.width = window.innerWidth;
            canvas.height = window.innerHeight;
            const ctx = canvas.getContext('2d');

            var img = document.createElement("img");
            img.src = url1;

            img.onload = async function () {
              //refixing the width and height
              canvas.width = img.width;
              canvas.height = img.height;

              ctx.drawImage(img, 0, 0)
              ctx.fillStyle = 'white';
              ctx.fillRect(10, 10, 180, 60);
              ctx.fillStyle = 'black';
              ctx.font = '10px Arial';
              ctx.fillText("GPS Coordinates", 20, 25);

              let s1 = gpsLive && gpsLive[0] + "," + gpsLive[1]
              ctx.font = '15px Arial';
              ctx.fillText(s1, 20, 40);

              s1 = new Date().toLocaleString('en-IN')
              ctx.font = '15px Arial';
              ctx.fillText(s1, 20, 55);
            }
            img.src = url1;

            window.setTimeout(function () {
              canvas.toBlob((processedBlob) => {

                let image1 = new File([processedBlob], fname1, { type: "image/jpeg" })

                let url1 = canvas.toDataURL("image/jpeg", 0.4);

                // var link = document.createElement('a');
                // link.download = 'filename.jpg';
                // link.href = url1
                // link.click();

                imageList[l1[0]] = { image1, url1, fname1 }

                setDummy(Math.random())
              }, 'image/jpeg')

            }, 1000)
            setDummy(Math.random())
          }}
        />
      </div>
    )
  }
  const checkbox = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return (
      <FormControlLabel id={l1[0] + "label"} title={data.irc_help_tool}
        style={{
          fontSize: "16px",
          fontWeight: "600",
          color: "rgba(46, 75, 122, 1)",
        }}
        label={l2[0]}
        control={
          <Checkbox title={data.irc_help_tool}
            id={l1[0]} required={data.field_type == "Mandatory"}
            onChange={(e) => {
              let localCopy = new Map()
              localCopy = checkMap
              localCopy.set(l1[0], e.target.checked)
              setDummy(Math.random())
              setcheckMap(localCopy)
            }}
            checked={checkMap && checkMap.get(l1[0]) ?
              ((checkMap.get(l1[0]) == "true" || checkMap.get(l1[0]) == true) ? true : false) : false}
          />
        }
      />
    )
  }
  // const combo = (data) => {
  //   let l1 = Object.keys(data)
  //   let l2 = Object.values(data)
  //   console.log(l1,l2,"klkl")
  //   return (
  //     <FormControl className="dFlexCombo" fullWidth title={data.irc_help_tool} style={{ display: "flex" }}>
  //       <InputLabel id={"label" + l1[0]}>{l2[0]}</InputLabel>
  //       <elect className="dFlex" id={l1[0]} required={data.field_type == "Mandatory"} title={data.irc_help_tool}
  //         onOpen={() => {
  //           if (data.conditions != "NA")
  //             populateDependList(data)
  //           setDummy(Math.random())
  //         }}
  //         onClick={() => {
  //           if (data.conditions != "NA")
  //             populateDependList(data)
  //           setDummy(Math.random())
  //         }}
  //         onChange={(e) => {
  //           let localCopy = new Map()
  //           localCopy = comboMap
  //           localCopy.set(l1[0], e.target.value)
  //           setDummy(Math.random())
  //           setcomboMap(localCopy)
  //         }}
  //         value={comboMap && comboMap.get(l1[0]) ? comboMap.get(l1[0]) : ''}
  //       //value={"Desirable"} 
  //       >
  //         {
  //           comboList && comboList[l1[0]] && comboList[l1[0]].map((x, i) =>
  //             <MenuItem key={x} value={x} title={comboIRC[l1[0]][i]} >
  //               {x}
  //               <div style={{ display: "flex", alignItems: "center" }}>
  //                 {" "}
  //                 <InfoOutlineIcon color="primary" fontSize="small" width="20px" height="20px"
  //                   onClick={(e) => {
  //                     handleClick(e);
  //                     if (anchorEl != null) {
  //                       setAnchorEl(null)
  //                     }
  //                     setPopContent(comboIRC[l1[0]][i])
  //                   }} />
  //               </div>
  //             </MenuItem>
  //           )
  //         }
  //       </Select>
  //     </FormControl>
  //   )
  // }

  const combo = (data) => {
    const keys = Object.keys(data);
    const values = Object.values(data);
    const fieldKey = keys[0];
    const labelText = values[0];
  console.log(values,'values')
    // Use Autocomplete for "Issues" OR "Marking Name"
    const isSearchable = labelText === "Issues" || labelText == "Marking Name " ||labelText=="Sign Name ";
  
    const currentValue = comboMap?.get(fieldKey) || '';
  
    const handleOpen = () => {
      if (data.conditions !== "NA") populateDependList(data);
      setDummy(Math.random());
    };
  
    const handleChange = (newValue) => {
      const localCopy = new Map(comboMap);
      localCopy.set(fieldKey, newValue || '');
      setcomboMap(localCopy);
      setDummy(Math.random());
    };
  
    if (isSearchable) {
      return (
        <FormControl fullWidth className="dFlexCombo" title={data.irc_help_tool}>
          <Autocomplete
            disablePortal
            id={`auto-${fieldKey}`}
            options={comboList?.[fieldKey] || []}
            value={currentValue}
            onChange={(e, val) => handleChange(val)}
            onOpen={handleOpen}
            renderInput={(params) => (
              <TextField
                {...params}
                label={labelText}
                required={data.field_type === "Mandatory"}
                title={data.irc_help_tool}
              />
            )}
            renderOption={(props, option) => {
              const idx = comboList?.[fieldKey]?.indexOf(option) ?? -1;
              const info = idx >= 0 ? comboIRC?.[fieldKey]?.[idx] : '';
              return (
                <li {...props} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
                  <span>{option}</span>
                  {info && (
                    <InfoOutlineIcon
                      color="primary"
                      fontSize="small"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleClick(e);
                        if (anchorEl != null) setAnchorEl(null);
                        setPopContent(info);
                      }}
                    />
                  )}
                </li>
              );
            }}
          />
        </FormControl>
      );
    }
  
    return (
      <FormControl fullWidth className="dFlexCombo" title={data.irc_help_tool}>
        <InputLabel id={`lbl-${fieldKey}`}>{labelText}</InputLabel>
        <Select
          id={fieldKey}
          label={labelText}
          required={data.field_type === "Mandatory"}
          value={currentValue}
          onChange={(e) => handleChange(e.target.value)}
          onOpen={handleOpen}
        >
          {comboList?.[fieldKey]?.map((opt, i) => {
            const info = comboIRC?.[fieldKey]?.[i] || '';
            return (
              <MenuItem key={opt} value={opt}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}>
                  {opt}
                  {info && (
                    <InfoOutlineIcon
                      color="primary"
                      fontSize="small"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleClick(e);
                        if (anchorEl != null) setAnchorEl(null);
                        setPopContent(info);
                      }}
                    />
                  )}
                </div>
              </MenuItem>
            );
          })}
        </Select>
      </FormControl>
    );
  };
  const fillComboList = (local, comboID) => {
    AxiosApp.post(url1 + "master_table_view", local)
      .then((response) => {
        //setIsload(false);
        let object = response.data.details;
        let x1 = [];
        let x2 = [];
        let x3 = [];
        if (response.data.statusCode == "200") {
          for (let index = 0; index < object.length; index++) {
            const element = object[index];
            x1.push(element.answer)
            x2.push(element.sub_q_id)
            x3.push(element.irc_help_tool)
          }
          comboList[comboID] = x1;
          comboIDList[comboID] = x2;
          comboIRC[comboID] = x3;
          setDummy(Math.random())
        } else {
          setAlert("error");
          setAlertMsg(response.data.status);
        }
      })
      .catch((error) => {
        setIsload(false);
        setAlert("error");
        setAlertMsg(error);
      });
  }
  const findComboList = () => {
    let fullData = state.details;
    /**
     * loop thru each object and find the combo objects
     * do axios and fill its state
     */
    for (let index = 0; index < fullData.length; index++) {
      const element = fullData[index];
      if (element.master_table == "Master_Table" || element.master_table == "Master Table") {
        let l1 = Object.keys(element)
        let l2 = Object.values(element)
        let l3 = l1[0].split(".")
        let local1 = { "section_id": l3[2], "q_id": l1[0] }
        if (element.conditions == "NA")
          fillComboList(local1, l1[0])
        else {
          comboList[l1[0]] = [];
          comboIDList[l1[0]] = [];
          comboIRC[l1[0]] = [];
        }
      }
    }
  }

  const populateDependList = (data) => {
    let l1 = Object.keys(data)
    let l2 = Object.values(data)

    let q_id = l1[0];
    let conditions = data.conditions;
    if (conditions == "NA") { return [] }
    // "Yes c.e.d.1"
    let l3 = conditions.split(" ")[1]
    let l4 = document.getElementById(l3).innerText;

    //search this l4 - 1. goto combolist[l3] , search l4, get index, search in comboidlist[]
    let index1 = comboList[l3].indexOf(l4)
    let subQIndex = 0;
    if (index1 != -1) {
      subQIndex = comboIDList[l3][index1]
    } else return

    //populate dependency dropdown
    let local = { "q_id": q_id, "sub_q_id": subQIndex }

    AxiosApp.post(url1 + "dependency", local)
      .then((response) => {
        //setIsload(false);
        let object = response.data.details;
        let x1 = [];
        let x2 = [];
        let x3 = [];
        if (response.data.statusCode == "200") {
          for (let index = 0; index < object.length; index++) {
            const element = object[index];
            x1.push(element.answer)
            x2.push(element.sub_q_id)
            x3.push(element.irc_help_tool)
          }
          comboList[q_id] = x1;
          comboIDList[q_id] = x2;
          comboIRC[q_id] = x3;
          setDummy(Math.random())
        } else {
          setAlert("error");
          setAlertMsg(response.data.status);
        }
      })
      .catch((error) => {
        setIsload(false);
        setAlert("error");
        setAlertMsg(error);
      });

  }
  useEffect(() => {
    findComboList();

    //api call to fetch the map
    loadStretchGeo();
    loadAuditorGeo();

    //state has data, then populate the form
    if (state.data && state.qids) {
      //populate the form
      // document.querySelector(`[id='${state.qids[0]}']`).value = state.data.gps;
      // setgpsAutoValue(state.data.gps)

      // document.querySelector(`[id='${state.qids[1]}']`).value = state.data.chainage;



      console.log("" + document.querySelector(`[id='${state.qids[2]}']`) + "Raghav..........");
       if(document.querySelector(`[id='${state.qids[2]}']`)!=null) {
        document.querySelector(`[id='${state.qids[2]}']`).value = state.data.issues;
       }

      let localCopy = new Map()
      localCopy = comboMap
      localCopy.set(state.qids[3], state.data.severity)
      localCopy.set(state.qids[4], state.data.priority)
      localCopy.set(state.qids[7], state.data.roadside)
      localCopy.set(state.qids[5], state.data.category)
      localCopy.set(state.qids[2], state.data.issues)
      setcomboMap(localCopy)
      setDummy(Math.random())

      let localCopy1 = new Map()
      localCopy1 = checkMap

      // localCopy1.set(state.qids[5], (state.data.general == "true" ? true : false))
      // let span1 = document.querySelector(`[id='${state.qids[5]}label']`).querySelector("span")
      // span1.classList.add("Mui-checked")

      localCopy1.set(state.qids[6], (state.data.critical == "true" ? true : false))
      let span1 = document.querySelector(`[id='${state.qids[6]}label']`).querySelector("span")
      span1.classList.add("Mui-checked")

      setcheckMap(localCopy1)
    }
  }, [])
  const loadStretchGeo = () => {
    let l1 = {
      "audit_type_id": state.auditObj.audit_type_id
    }
    AxiosApp.post(url1 + "total_stretch_kml", l1)
      .then((response) => {
        setIsload(false);
        let l1 = response.data;
        if (response.data.statusCode == "200") {
          setStretchGeo(response.data.location);
        }
      })
      .catch((error) => {
        setIsload(false);
        //setAlert("error");
        //setAlertMsg(error);
      });
  }
  const loadAuditorGeo = () => {
    let l1 = {
      "audit_id": state.auditObj.audit_id
    }
    AxiosApp.post(url1 + "auditor_stretch_kml", l1)
      .then((response) => {
        setIsload(false);
        let l1 = response.data;
        if (response.data.statusCode == "200") {
          setAuditorGeo(response.data.location);
        }
      })
      .catch((error) => {
        setIsload(false);
        //setAlert("error");
        //setAlertMsg(error);
      });
  }

  // const getGeoFloatMapData = () =>{
  //   let l1 = {
  //     "audit_id":state.auditObj.audit_id
  //   }
  //   AxiosApp.post(url1 + "audit_kml", l1,
  //   {
  //     responseType: 'arraybuffer',
  //     contentType: 'application/zip'
  //   })
  //   .then(data => {
  //     JSZip.loadAsync(data.data)
  //       .then(zip => {
  //         setIsload(false);

  //         // Filter the files to only include image files
  //         const imageFiles = Object.keys(zip.files)
  //           .filter(filename => /\.(kml)$/i.test(filename));

  //         imageFiles.forEach((filename, index) => {            
  //           zip.file(filename)
  //             .async('blob')
  //             .then(blob => {                                 
  //               setKmlUrl(URL.createObjectURL(blob))
  //             });
  //         })
  //         setDummy(Math.random())
  //       })
  //       .catch(e => { console.log(e); setIsload(false); })
  //   })
  //   .catch(error => { setIsload(false); console.error(error) });
  // }
  const fillFloatMap = () => {
    if (map != '')
      map.remove()

    let centerpoint = [21.0000, 78.0000];
    if (auditorGeo) {
      centerpoint = [12.974741135, 77.326700227]
    }
    map = new L.map('mapFloat',
      {
        center: centerpoint, // india coordinates 
        zoom: 5,
        zoomControl: true,
        trackResize: true,
      })
    const osm = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png');

    map.addLayer(osm);

    var geojsonMarkerOptions = {
      radius: 8,
      fillColor: "#ff0000",
      color: "#ff0000",
      weight: 1,
      opacity: 1,
      fillOpacity: 0.8
    };
    var geojsonMarkerOptions1 = {
      radius: 8,
      fillColor: "#00ff00",
      color: "#00ff00",
      weight: 1,
      opacity: 1,
      fillOpacity: 0.8
    };

    if (stretchGeo) {
      L.geoJson(stretchGeo, {
        pointToLayer: function (feature, latlng) {
          return L.circleMarker(latlng, geojsonMarkerOptions);
        },
        onEachFeature: function (feature, layer) {
          // let t1 = Object.keys(feature)
          // let t2 = Object.values(feature)
          // let t3 = ''

          // for(let index = 0; index < t2.length; index++) {
          //   if(index == 0) t3 = t1[index] + ": " + t2[index]
          //   else t3 = t3 + "<br/>" + t1[index] + ": " + t2[index]
          // }
          // layer.bindPopup(t3);
          layer.bindPopup(
            '<h3>Stretch Details</h3>' +
            '<h3>Stretch name: ' + feature.stretch_name +
            '<br/><h3>Stretch ID: ' + feature.audit_type_id + '</h3>' +
            '<br/><h3>Chainage: ' + feature.chainage + '</h3>' +
            '<br/><h3>Description: ' + (feature.description ? feature.description : "") + '</h3>' +
            '<br/><h4>Geo Points:' + feature.geometry.coordinates[0] + "," + feature.geometry.coordinates[1]);

        },
        style: function (feature) {
          return { color: "#6a5acd", fillColor: "#6a5acd" };
        }
      }).addTo(map);
    }
    if (auditorGeo) {
      L.geoJson(auditorGeo, {
        pointToLayer: function (feature, latlng) {
          return L.circleMarker(latlng, geojsonMarkerOptions1);
        },
        onEachFeature: function (feature, layer) {
          // let t1 = Object.keys(feature.properties)
          // let t2 = Object.values(feature.properties)
          // let t3 = ''

          // for(let index = 0; index < t2.length; index++) {
          //   if(index == 0) t3 = t1[index] + ": " + t2[index]
          //   else t3 = t3 + "<br/>" + t1[index] + ": " + t2[index]
          // }
          // layer.bindPopup(t3);
          layer.bindPopup(
            '<h3>Audit Details</h3>' +
            '<h3>Stretch ID: ' + feature.stretch_name +
            '<br/><h3>Audit ID: ' + feature.audit_id + '</h3>' +
            '<br/><h3>Chainage: ' + feature.chainage + '</h3>' +
            '<br/><h3>Description: ' + (feature.description ? feature.description : "") + '</h3>' +
            '<br/><h4>Geo Points:' + feature.geometry.coordinates[0] + "," + feature.geometry.coordinates[1]);

        },
        style: function (feature) {
          return { fillColor: "#ef9ced", color: "#6a5acd" };
        }
      }).addTo(map);
    }
    if (gpsLive)
      L.marker(gpsLive).addTo(map).bindPopup('Your Current Location')
  }
  return (
    <div>
      <div>
        <p style={{
          display: "none"
        }}>{dummy}</p>
        <CustomLoader show={isload} />
        {alert != "" && (
          // <CustomAlerts msg={alertMsg} severity={alert}/>
          <CustomAlerts onClose={() => setAlert("")}>
            <p
              style={{
                fontSize: "17px",
                fontWeight: "700",
                marginTop: "17px",
              }}
            >
              {alertMsg}
            </p>
          </CustomAlerts>
        )}
        <AuditorHeader />
        {/* <DraggableCore>
          <div draggable
            style={{
              boxShadow:
                "rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px",
              borderRadius: "10px",
              display: "flex",
              justifyContent: "center",
              padding: "9px",
              position: "absolute",
              bottom: "20px",
              right: "10px",
              zIndex: "1000",
              backgroundColor: "white",
            }}
            onClick={(e) => {
              handleOpen()
              window.setTimeout(() => {
                fillFloatMap()
              }, 1000)
            }
            }
          >
            Way Points
          </div>
        </DraggableCore> */}
        <DraggableCore>
          <div
            draggable
            style={{
              boxShadow:
                "rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px",
              borderRadius: "10px",
              display: "flex",
              justifyContent: "center",
              padding: "9px",
              position: "absolute",
              bottom: "20px",
              right: "10px",
              zIndex: "1000",
              backgroundColor: "white",
              cursor: "pointer",           // ← helps mobile recognize it as interactive
              touchAction: "manipulation", // ← important for mobile (prevents double-tap zoom, allows fast click)
            }}
            onPointerDown={(e) => {
              // Optional: you can add visual feedback here (scale, color change, etc.)
            }}
            onPointerUp={(e) => {
              // Only trigger if it wasn't a drag
              // (very short press → treat as tap)
              handleOpen();
              window.setTimeout(() => {
                fillFloatMap();
              }, 1000);
            }}
            onClick={(e) => {
              // Keep this as fallback for desktop
              handleOpen();
              window.setTimeout(() => {
                fillFloatMap();
              }, 1000);
            }}
          >
            Way Points
          </div>
        </DraggableCore>
        <CustomLoader show={isload} />
        {alert != "" && (
          // <CustomAlerts msg={alertMsg} severity={alert}/>
          <CustomAlerts onClose={() => setAlert("")}>
            <p
              style={{
                fontSize: "17px",
                fontWeight: "700",
                marginTop: "17px",
              }}
            >
              {alertMsg}
            </p>
          </CustomAlerts>
        )}
        <div
          style={{
            backgroundColor: "#f4f7fa",
            minHeight: "100vh",
            padding: "20px",
          }}
        >
          <div
            style={{
              display: "flex",
              //   justifyContent: "space-between",
              gap: "20px",
            }}
          >
            <ArrowBackIcon onClick={() => { imageList = {}; navigate(-1) }} />
            <span>{state.auditObj.audit_id}</span>
          </div>
          <div
            style={{
              position: "relative",
              border: "0.5px solid rgba(127, 163, 222, 0.3)",
              // height: "300px",
              marginTop: "20px",
              borderRadius: "20px",
              padding: "20px",
              marginBottom: '10%'
            }}
          >
            <div
              style={{
                position: "absolute",
                top: "-12px",
                left: "28px",
                backgroundColor: "#f4f7fa",
                color: "rgba(46, 75, 122, 1)",
              }}
            >
              Section Audit Details - {state.sectionName}
            </div>
            {console.log(state, 'state')}
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "10px",
              }}
            >
              {
                state.details.map((x, i) => {
                  return (
                    <div style={{ display: "flex", flexDirection: "row" }}>
                      {findDatatype(state.details[i])}
                      <div style={{ display: "flex", alignItems: "center" }}>
                        {" "}
                        <InfoOutlineIcon color="primary" fontSize="small" width="50px" height="50px"
                          onClick={(e) => {
                            handleClick(e);
                            if (anchorEl != null) {
                              setAnchorEl(null)
                            }
                            setPopContent(state.details[i].irc_help_tool)
                          }} />
                      </div>
                    </div>
                  )
                })
              }

              <div style={{ display: "flex", marginBottom: '40px' }}>
                <Button
                  style={{
                    backgroundColor: "rgba(14, 176, 0, 1)",
                    color: "white",
                    width: "100px",
                    margin: "auto",
                  }}
                  onClick={() => {
                    handleSaveSection()
                  }}
                >
                  Save
                </Button>
              </div>
            </div>
          </div>
        </div>
        <Modal
          open={open}
          onClose={handleClose}
          aria-labelledby="modal-modal-title"
          aria-describedby="modal-modal-description"
        >
          <Box sx={style}>
            <div style={{
              border: "1px solid black",
              width: "100%",
              height: "90%"
            }} id="mapFloat">
            </div>{" "}
            <div style={{ display: "flex", justifyContent: "space-between" }}>
              <div style={{ display: "flex" }}>
                <div style={{
                  display: "flex",
                }}>
                  <div style={{
                    width: "10px",
                    height: "10px",
                    borderRadius: "50%",
                    background: "#6a5acd",
                    color: "#6a5acd",
                    margin: "15px",
                    marginLeft: "10px"
                  }}></div>
                  <span style={{ margin: "10px", marginLeft: "0px" }}>Stretch</span>
                </div>
                <div style={{
                  display: "flex",
                }}>
                  <div style={{
                    width: "10px",
                    height: "10px",
                    borderRadius: "50%",
                    background: "#ef9ced",
                    color: "#ef9ced",
                    margin: "15px",
                    marginLeft: "10px"
                  }}></div>
                  <span style={{ margin: "10px", marginLeft: "0px" }}>Audit</span>
                </div>
              </div>
              <Button
                variant="contained"
                color="primary"
                size="large"
                style={{
                  backgroundColor: "rgb(46, 75, 122)",
                  color: "white",
                  marginTop: "15px",
                }}
                onClick={() => handleClose()}
              >
                Close
              </Button>
            </div>
          </Box>
        </Modal>
      </div>
      <Popover
        id={id}
        open={open1}
        anchorEl={anchorEl}
        onClose={handleClose1}
        anchorOrigin={{
          vertical: 'bottom',
          horizontal: 'left',
        }}
      >
        <Typography sx={{ p: 2 }}>{popcontent}</Typography>
      </Popover>
    </div>
  );
}

export default SurveyformTwo;
