import React, { useEffect,useState } from "react";
import {
  Accordion,FormControlLabel,Checkbox,
  AccordionDetails,
  AccordionSummary,
  Box, NumberInput,
  Button,
  Modal,FormControl,Select,MenuItem,InputLabel,
  TextField,Popover,
  Typography,
} from "@mui/material";
import { DateTimePicker } from '@mui/x-date-pickers';
import { LocalizationProvider } from '@mui/x-date-pickers-pro'; 
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import Draggable from "react-draggable";
import mapimg from "../../../Assets/mapgroup.png";
import { useNavigate,useLocation } from "react-router-dom";
import AuditorHeader from "../AuditorHeader/AuditorHeader";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import AxiosApp from "../../../common/AxiosApp";
import CustomAlerts from "../../../common/CustomAlerts";
import CustomLoader from "../../../common/customLoader";
import InfoOutlineIcon from '@mui/icons-material/InfoOutlined';
import { url1 } from "../../../App";

var comboList = {};
var comboIDList = {};
var comboIRC = {};
var imageList = {};
var gpsLive = ['','']
navigator.geolocation.getCurrentPosition((position) =>{
  gpsLive[0] = position.coords.latitude.toFixed(5);
  gpsLive[1] =  position.coords.longitude.toFixed(5);      
});
function SurveyformThree() {
    const [popcontent, setPopContent] = React.useState('')
  const [anchorEl, setAnchorEl] = React.useState(null);

  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };

  const handleClose1 = () => {
    setAnchorEl(null);
  };

  const open1 = Boolean(anchorEl);
  const id = open1 ? 'simple-popover' : undefined;
  const navigate = useNavigate();
  const {state} = useLocation()

  const [sectionNames, setSectionNames] = useState([])
  const [sectionCategoryNames, setSectionCategoryNames] = useState([])
  
  //if(state.sNameList) setSectionNames(state.sNameList)
  //if(state.sCatList) setSectionCategoryNames(state.sCatList)

  //common
  const [isload, setIsload] = useState("");
  const [alert, setAlert] = useState("");
  const [alertMsg, setAlertMsg] = useState("");
  const [dummy, setDummy] = useState(0)
  const [gpsAutoValue, setgpsAutoValue] = useState([])
  const findDatatype = (x)=>{
    //if custom, its textbox
    //if mastertable, its combobox
    //if dependency is there, make sure to call another api to address dependency 
    let k1 = Object.keys(x)   
    let v1 = Object.values(x)
    /**
     * C.E.B.2: "Chainage (km)"
        conditions: "NA"
        data_type: "Numerical (Special Character)"
        field_type: "Optional"
        functionality: "Numerical Box"
        irc_help_tool: "Enter the Chainage Value in this Format (170+000)"
        master_table: "Custom"
     */
    let v2 = v1[4]
    if(v1[7] == "DD/MM/YY,hh:mm"){
      return datefield1(x)
    } else if(v2 == "Dropdown/ Radio Button"){
      return combo(x)
    } else if (v2 == "Numerical Box"){
      return decimal(x)
    } else if (v2 == "Autogenerated"){
      return gpsAuto(x)
    } else if(v2 == "Text Area") {
      return multiline(x)
    } else if(v2 == "Checkbox" || v2 == "Check Box") {
      return checkbox(x)
    } else if(v2 == "Camera/ Upload") {
      return upload(x)
    } else {
      return(<></>)
    }
    //for latlong, use upload button
  }
  const handleSaveSection = () =>{
    //form the data to post
    let local = state.details
    let payload1 = {}
    let temp = "";
    let rt = [];
    let imageFilenames = [];
    let formData = new FormData();
    for (let index = 0; index < local.length; index++) {
      const element = local[index];
      let id = Object.keys(element)[0]
      let value = element.functionality;
      switch(value){
        case "Dropdown/ Radio Button":{
          temp = document.getElementById(id).innerText          
          payload1[id] = temp;
          break;
        }
        case "Text Area":
        case "Numerical Box":
        case "Autogenerated":{ //gps
          temp = document.getElementById(id).value
          payload1[id] = temp;
          break;
        }
        case "Checkbox":{
          temp = document.getElementById(id).value          
          if(temp == "on") temp = true;
          else temp = false;
          payload1[id] = temp;          
          break;
        }
        case "Camera/ Upload":{
          console.log(imageList[id])
          imageFilenames.push(imageList[id]["fname1"])
          formData.append([imageList[id]["fname1"]],imageList[id]["image1"])
          temp = "image";
          payload1[id] = "Image";
          break;
        }
      }
      if(element.field_type == "Mandatory" && value != "Checkbox"){
        if(temp == ""){
          setAlert("success")
          setAlertMsg("Mandatory fields are not entered")
          return;
        }
      }

      let cd1 = element.conditions;
      if(cd1 != "NA"){
        cd1 = cd1.split(" ")[1]
        let s1 = document.getElementById(cd1).innerText
        let str1 = "";
        let str2 = "";
        //search s1 in comboIDList
        let index1 = comboList[cd1].indexOf(s1)
        let subQIndex = 0;
        if(index1 != -1){
          str1 = comboIDList[cd1][index1]
        }

        let s2 = document.getElementById(id).innerText
        //search s2 in comboIDList
        index1 = comboList[id].indexOf(s2)
        subQIndex = 0;
        if(index1 != -1){
          str2 = comboIDList[id][index1]
        }        
        
        let str3 = str1.concat(".").concat(str2)
        rt.push(str3)
      }
    }
    if(imageFilenames.length >= 0){
        payload1["file_name"] = imageFilenames;
    }
    //axios post
    let section = (Object.keys(state.details[0])[0]).split(".")[2]
    console.log(rt)
    formData.append("audit_id",state.auditObj.audit_id)
    formData.append("auditor_id",state.auditObj.auditor)                                                                            
    formData.append("section_id",section)
    formData.append("answers",JSON.stringify(payload1))       
    formData.append("retrieval_ids",JSON.stringify(rt))
    formData.append("submitted_on",new Date().toISOString().slice(0, 10).split('-').reverse().join('-'))
    const config = {     
      headers: { 'content-type': 'multipart/form-data' }
    }
    //share gps
    let check1 = "";
    let check2 = ""
    try {
      check1 = Object.keys(local[0])[0]
      //if(check1.split(".")[3] == '1' && local[0][check1].search("GPS")> -1){
        if(local[0][check1].search("GPS")> -1){
        check2 = document.getElementById(check1).value;
        // let regex = /^\d+\.\d+$/;
        // if(!(regex.test(check2))) {
        //   setAlert("error");
        //   setAlertMsg("Please enter correct format for GPS, eg:0.200");
        //   return;
        // }
      }
    } catch (error) {      
    }
    //do string search and find the answer
    formData.append('gps_location',check2)

    //share chainage
    let v1 = ""
    try {
      if(document.querySelectorAll("[title*='Chainage']") &&
      document.querySelectorAll("[title*='Chainage']")[0] &&
      document.querySelectorAll("[title*='Chainage']")[0].getElementsByTagName("input") &&
      document.querySelectorAll("[title*='Chainage']")[0].getElementsByTagName("input")[0].value)
      {
        v1 = document.querySelectorAll("[title*='Chainage']")[0]
    .getElementsByTagName("input")[0].value;
        let regex = /^\d+\+\d+$/;
        if(!(regex.test(v1))) {
          setAlert("error");
          setAlertMsg("Please enter correct format for chainage, eg:0+200");
          return;
        }else {
          v1 = v1.replace("+",".")
        }
    }
    } catch (error) {   
       
    }
    //do string search and find the answer
    formData.append('chainage',v1)
    formData.append("sub_section", "")
    //share question '4' ends, road side
    check1 = "";
    check2 = "";
    try {
      check1 = Object.keys(local[3])[0]
      if(check1.split(".")[3] == '4' && local[3][check1] == "Road Side"){
        check2 = document.getElementById(check1).innerText;
      }
    } catch (error) {
      
    }
    formData.append("roadside",check2);
    formData.append("obs_category", "")

    formData.append("live_gps",gpsLive)
    console.log(formData)
    AxiosApp.post(url1 + "answer",formData,config)
      .then((response) => {
        setIsload(true)
        if (response.data.statusCode == "200") { 
          setIsload(false);
          setAlert("success");
          setAlertMsg(response.data.status);     
          // if(localStorage.setItem("rsa_type") === 
          
              if (localStorage.getItem("rsa_type") == 'auditor') {
            navigate('/Auditor_dashboard')
          } else if(localStorage.getItem("rsa_type")=="ae") {
            navigate('/Ae_dashboard')
          } else if(localStorage.getItem("rsa_type")=="field user") {
            navigate('/fe_audit')
          }
          // navigate("/Auditor_Audit",{state:{sNameList:sectionNames,
          //   sCatList:sectionCategoryNames}})
        } else {
          setAlert("error");          
          // navigate(-1,{state:{showObj:state.auditObj}})
          setAlertMsg(response.data.status);
        }
      })
      .catch((error) => {
        setIsload(false);
        setAlert("error");        
        navigate(-1,{state:{showObj:state.auditObj}})
        setAlertMsg(error);
      }); 

  }
  const datefield1 = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <FormControl fullWidth title={data.irc_help_tool}>
      <LocalizationProvider dateAdapter={AdapterDayjs}>     

      <DateTimePicker required disableFuture label={l2[0]}
          //onChange={} 
          closeOnSelect={true}
          format="DD-MM-YYYY HH:mm"
          ampm={false}
          slotProps={{
              textField: {
                required: true,
                id:l1[0]
              },
            }}/>
      </LocalizationProvider>
      </FormControl>
    )
  }
  const text = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <TextField
          fullWidth id={l1[0]} title={data.irc_help_tool}
          label={l2[0]}
          required = {data.field_type == "Mandatory"}
          variant="outlined"
        />
    )
  }
  const decimal = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <TextField id={l1[0]} label={l2[0]}  
        title={data.irc_help_tool}               
        required = {data.field_type == "Mandatory"}
      /> 
    )
  }   
  const multiline = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <TextField title={data.irc_help_tool}
          fullWidth multiline
          label={l2[0]} id={l1[0]}
          required = {data.field_type == "Mandatory"} 
          variant="outlined"
        />
    )
  }
  const gpsAuto = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(<div style={{
      display:"flex"
    }}>
      <TextField id={l1[0]} label={l2[0]}  
        title={data.irc_help_tool}               
        required = {data.field_type == "Mandatory"}
        value={gpsAutoValue}
        onChange={(e)=>setgpsAutoValue(e.target.value)}    
      /> 
      <Button onClick={(e)=>setgpsAutoValue(gpsLive)}>Click to Fetch GPS Coordinates</Button></div>
    )
  }  
  const upload=(data)=>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <div style={{
        display:"flex"
      }}>
        <img
          style={{
            width: "200px",
            height: "200px",
            backgroundColor: "white",
            backgroundImage: imageList && imageList[l1[0]] && imageList[l1[0]].url1,
          }}
          src={imageList && imageList[l1[0]] && imageList[l1[0]].url1}
          alt={""}
        />
      <Button
        onClick={(e) => {
          document.getElementById(l1[0]).click();
        }} title={data.irc_help_tool}
      >
        {"Upload"}
        {/* Upload {l2[0]} */}
      </Button>
      <input
        type="file" title={data.irc_help_tool}
        //accept="image/*"
        id={l1[0]}
        style={{ display: "none" }}
        onChange={(e) => {
          let image1 = e.target.files[0]
          let url1 = URL.createObjectURL(e.target.files[0]);
          //need to save as this 
          let fname1 = l1[0] + ".jpg"; //e.target.files[0].name;

          imageList[l1[0]] = {image1,url1,fname1}
          setDummy(Math.random())
        }}
      />
      </div>
    )
  }
  const checkbox=(data)=>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <FormControlLabel 
          style={{
            fontSize: "16px",
            fontWeight: "600",
            color: "rgba(46, 75, 122, 1)",
          }}          
          label={l2[0]}                        
          control={                        
            <Checkbox  title={data.irc_help_tool}                       
            id={l1[0]} required = {data.field_type == "Mandatory"}/>
          }
       />
    )
  }
  const combo = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data)
    return(
      <FormControl  className="dFlexCombo" fullWidth title={data.irc_help_tool} style={{ display: "flex" }}>
        <InputLabel>{l2[0]}</InputLabel>
        <Select className="dFlex" id={l1[0]} title={data.irc_help_tool} required = {data.field_type == "Mandatory"}
          onClick={()=>{
            if(data.conditions != "NA")
             //only in second call, value is loaded coz,
              // state is not maintained in this form as the fields are dynamic         
              populateDependList(data)
              populateDependList(data)
          }}
        >
          {
          comboList && comboList[l1[0]] && comboList[l1[0]].map((x,i)=>                    
            <MenuItem key={x} title={comboIRC[l1[0]][i]} value={x}>{x}</MenuItem>
          )
          }
        </Select>
      </FormControl>
    )
  }
  const fillComboList = (local,comboID) =>{    
    AxiosApp.post(url1 + "master_table_view",local)
      .then((response) => {
        //setIsload(false);
        let object = response.data.details;
        let x1 = [];
        let x2 = [];
        let x3 = [];
        if (response.data.statusCode == "200") { 
          for (let index = 0; index < object.length; index++) {
            const element = object[index];
            x1.push(element.answer)
            x2.push(element.sub_q_id)
            x3.push(element.irc_help_tool)
          }
          comboList[comboID] = x1;
          comboIDList[comboID] = x2;
          comboIRC[comboID] = x3;
          setDummy(Math.random())     
        } else {
          setAlert("error");
          setAlertMsg(response.data.status);
        }
      })
      .catch((error) => {
        setIsload(false);
        setAlert("error");
        setAlertMsg(error);
      }); 
  }
  const findComboList = () =>{
    let fullData = state.details;
    /**
     * loop thru each object and find the combo objects
     * do axios and fill its state
     */
    for (let index = 0; index < fullData.length; index++) {
      const element = fullData[index];
      if(element.master_table == "Master_Table"  || element.master_table == "Master Table"){
        let l1 = Object.keys(element)
        let l2 = Object.values(element)
        let l3 = l1[0].split(".")
        let local1 = {"section_id":l3[2],"q_id":l1[0]}
        fillComboList(local1,l1[0])
      }
    }
  }

  const populateDependList = (data) =>{
    let l1 = Object.keys(data)
    let l2 = Object.values(data) 

    let q_id = l1[0];
    let conditions = data.conditions;
    if(conditions == "NA"){ return []}
    // "Yes c.e.d.1"
    let l3 = conditions.split(" ")[1]
    let l4 = document.getElementById(l3).innerText;

    //search this l4 - 1. goto combolist[l3] , search l4, get index, search in comboidlist[]
    let index1 = comboList[l3].indexOf(l4)
    let subQIndex = 0;
    if(index1 != -1){
      subQIndex = comboIDList[l3][index1]
    } else return

    //populate dependency dropdown
    let local = {"q_id":q_id, "sub_q_id":subQIndex }

    AxiosApp.post(url1 + "dependency",local)
      .then((response) => {
        //setIsload(false);
        let object = response.data.details;
        let x1 = []
        let x2 = [];
        if (response.data.statusCode == "200") { 
          for (let index = 0; index < object.length; index++) {
            const element = object[index];
            x1.push(element.answer)
            x2.push(element.sub_q_id)
          }
          comboList[q_id] = x1;
          comboIDList[q_id] = x2;
          setDummy(Math.random())     
        } else {
          setAlert("error");
          setAlertMsg(response.data.status);
        }
      })
      .catch((error) => {
        setIsload(false);
        setAlert("error");
        setAlertMsg(error);
      }); 

  }
  useEffect(()=>{
    findComboList()
  },[])
  
  return (
    <div>
    <div>
       <CustomLoader show={isload} />
      {alert != "" && (
        // <CustomAlerts msg={alertMsg} severity={alert}/>
        <CustomAlerts onClose={() => setAlert("")}>
          <p
            style={{
              fontSize: "17px",
              fontWeight: "700",
              marginTop: "17px",
            }}
          >
            {alertMsg}
          </p>
        </CustomAlerts>
      )}
      <AuditorHeader />
      <div
        style={{
          backgroundColor: "#f4f7fa",
          minHeight: "100vh",
          padding: "20px",
        }}
      >
        <div
          style={{
            display: "flex",
            //   justifyContent: "space-between",
            gap: "20px",
          }}
        >
          <ArrowBackIcon onClick={() => navigate(-1,)} />
             <span>{state.auditObj.audit_id}</span>
        </div>
        <div
          style={{
            position: "relative",
            border: "0.5px solid rgba(127, 163, 222, 0.3)",
            // height: "300px",
            marginTop: "20px",
            borderRadius: "20px",
            padding: "20px",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: "-12px",
              left: "28px",
              backgroundColor: "#f4f7fa",
              color: "rgba(46, 75, 122, 1)",
            }}
          >
            Audit Details - {state.sectionName}
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              gap: "10px",
            }}
          >
            {
              state.details.map((x,i)=>{
                 return (
                  <div style={{ display: "flex", flexDirection: "row" }}>
                    {findDatatype(state.details[i])}
                    <div style={{ display: "flex", alignItems: "center" }}>
                      {" "}
                      <InfoOutlineIcon color="primary" fontSize="small" width="50px" height="50px"
                        onClick={(e) => {
                          handleClick(e);
                          if (anchorEl != null) {
                            setAnchorEl(null)
                          }
                          setPopContent(state.details[i].irc_help_tool)
                        }} />
                    </div>
                  </div>
                )
              })
            }

            <div style={{ display: "flex" }}>
              <Button
                style={{
                  backgroundColor: "rgba(14, 176, 0, 1)",
                  color: "white",
                  width: "100px",
                  margin: "auto",
                }}
                onClick={()=>{
                  handleSaveSection()
                }}
              >
                Save
              </Button>
            </div>
            <br/>
            <br/>
            <br/>
          </div>
        </div>
      </div>
    </div>
       <Popover
            id={id}
            open={open1}
            anchorEl={anchorEl}
            onClose={handleClose1}
            anchorOrigin={{
              vertical: 'bottom',
              horizontal: 'left',
            }}
          >
            <Typography sx={{ p: 2 }}>{popcontent}</Typography>
          </Popover>
    </div>
  );
}

export default SurveyformThree;
